=== kononir/tariffsParsing/src/main/resources/tariffs_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/tariffs"
        xmlns:tns="http://www.epam.com/tariffs"
        elementFormDefault="qualified">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    
    <element name="tariff" type="tns:Tariff" abstract="true"/>
    <element name="calling-tariff" type="tns:CallingTariff" substitutionGroup="tns:tariff"/>
    <element name="internet-tariff" type="tns:InternetTariff" substitutionGroup="tns:tariff"/>
    
    <simpleType name="Operator">
        <restriction base="string">
            <enumeration value="MTS"/>
            <enumeration value="Velcom"/>
            <enumeration value="Life"/>
        </restriction>
    </simpleType>

    <complexType name="Cost">
        <sequence>
            <element name="rubles" type="nonNegativeInteger"/>
            <element name="kopecks">
                <simpleType>
                    <restriction base="nonNegativeInteger">
                        <maxInclusive value="99"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="Tariff">
        <sequence>
            <element name="payroll" type="tns:Cost"/>
            <element name="connecting-cost" type="tns:Cost"/>
        </sequence>

        <attribute name="name" type="string"/>
        <attribute name="operator" type="tns:Operator" default="MTS"/>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="[A-F0-9]{8}"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="CallCosts">
        <sequence>
            <element name="call-inside-the_network" type="tns:Cost"/>
            <element name="call-outside-the-network" type="tns:Cost"/>
            <element name="call-to-favourite-number" type="tns:Cost"/>
        </sequence>
    </complexType>

    <complexType name="CallingTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <sequence>
                    <element name="call-costs" type="tns:CallCosts"/>
                    <element name="favorite-numbers-count" type="nonNegativeInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="InternetSpeedType">
        <restriction base="string">
            <enumeration value="unlimited"/>
            <enumeration value="limited"/>
        </restriction>
    </simpleType>

    <complexType name="InternetTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <sequence>
                    <element name="starting-number-of-MB" type="nonNegativeInteger"/>
                    <element name="cost-of-one-MB" type="tns:Cost"/>
                    <element name="speed-type" type="tns:InternetSpeedType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== kononir/tariffsParsing/src/test/resources/internet_tariff_all_are_filed.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.com/tariffs"
         xsi:schemaLocation="http://www.epam.com/tariffs tariffs_schema.xsd">

    <internet-tariff id="AAAAAAAD" name="Ğ¨ĞµĞ¹Ğº 1" operator="Life">
        <payroll>
            <rubles>11</rubles>
            <kopecks>90</kopecks>
        </payroll>
        <connecting-cost>
            <rubles>7</rubles>
            <kopecks>90</kopecks>
        </connecting-cost>
        <starting-number-of-MB>4000</starting-number-of-MB>
        <cost-of-one-MB>
            <rubles>0</rubles>
            <kopecks>0</kopecks>
        </cost-of-one-MB>
        <speed-type>limited</speed-type>
    </internet-tariff>
</tariffs>

=== kononir/tariffsParsing/src/test/resources/one_tariff.xml
<?xml version="1.0" encoding="UTF-8" ?>

<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.com/tariffs"
         xsi:schemaLocation="http://www.epam.com/tariffs tariffs_schema.xsd">

    <calling-tariff id="AAAAAAAA" name="Супер max">
        <payroll>
            <rubles>20</rubles>
            <kopecks>0</kopecks>
        </payroll>
        <connecting-cost>
            <rubles>5</rubles>
            <kopecks>0</kopecks>
        </connecting-cost>
        <call-inside-the-network>
            <rubles>0</rubles>
            <kopecks>0</kopecks>
        </call-inside-the-network>
        <call-outside-the-network>
            <rubles>0</rubles>
            <kopecks>0</kopecks>
        </call-outside-the-network>
        <call-to-favourite-number>
            <rubles>0</rubles>
            <kopecks>0</kopecks>
        </call-to-favourite-number>
        <favorite-numbers-count>0</favorite-numbers-count>
    </calling-tariff>
</tariffs>

=== kononir/tariffsParsing/src/test/resources/tariffs.xml
<?xml version="1.0" encoding="utf-8" ?>

<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.com/tariffs"
         xsi:schemaLocation="http://www.epam.com/tariffs tariffs_schema.xsd">

    <calling-tariff name="Супер max" id="AAAAAAAA">
        <payroll>
            <rubles>20</rubles>
            <kopecks>0</kopecks>
        </payroll>
        <connecting-cost>
            <rubles>5</rubles>
            <kopecks>0</kopecks>
        </connecting-cost>
        <call-costs>
            <call-inside-the_network>
                <rubles>0</rubles>
                <kopecks>0</kopecks>
            </call-inside-the_network>
            <call-outside-the-network>
                <rubles>0</rubles>
                <kopecks>0</kopecks>
            </call-outside-the-network>
            <call-to-favourite-number>
                <rubles>0</rubles>
                <kopecks>0</kopecks>
            </call-to-favourite-number>
        </call-costs>
        <favorite-numbers-count>0</favorite-numbers-count>
    </calling-tariff>
    
    <calling-tariff name="Пенсионный" operator="Velcom" id="AAAAAAAB">
        <payroll>
            <rubles>3</rubles>
            <kopecks>70</kopecks>
        </payroll>
        <connecting-cost>
            <rubles>5</rubles>
            <kopecks>0</kopecks>
        </connecting-cost>
        <call-costs>
            <call-inside-the_network>
                <rubles>0</rubles>
                <kopecks>5</kopecks>
            </call-inside-the_network>
            <call-outside-the-network>
                <rubles>0</rubles>
                <kopecks>17</kopecks>
            </call-outside-the-network>
            <call-to-favourite-number>
                <rubles>0</rubles>
                <kopecks>2</kopecks>
            </call-to-favourite-number>
        </call-costs>
        <favorite-numbers-count>5</favorite-numbers-count>
    </calling-tariff>
    
    <internet-tariff name="Бит" id="AAAAAAAC">
        <payroll>
            <rubles>8</rubles>
            <kopecks>95</kopecks>
        </payroll>
        <connecting-cost>
            <rubles>8</rubles>
            <kopecks>95</kopecks>
        </connecting-cost>
        <starting-number-of-MB>250</starting-number-of-MB>
        <cost-of-one-MB>
            <rubles>0</rubles>
            <kopecks>0</kopecks>
        </cost-of-one-MB>
        <speed-type>limited</speed-type>
    </internet-tariff>

    <internet-tariff name="Шейк 1" operator="Life" id="AAAAAAAD">
        <payroll>
            <rubles>11</rubles>
            <kopecks>90</kopecks>
        </payroll>
        <connecting-cost>
            <rubles>7</rubles>
            <kopecks>90</kopecks>
        </connecting-cost>
        <starting-number-of-MB>4000</starting-number-of-MB>
        <cost-of-one-MB>
            <rubles>0</rubles>
            <kopecks>0</kopecks>
        </cost-of-one-MB>
        <speed-type>limited</speed-type>
    </internet-tariff>
</tariffs>
